### ISSUE TITLE
Toggle line comments creates block comments instead of line comments

### ISSUE THREAD

**Issue by jvolker** [nadege/unity-shader-files#3] opened 2017-05-21 23:01 UTC
`Toggle line comments` creates block comments instead of line comments.

Not sure if this is related to this package, but I didn't have this issue with other file types. Please let me know if you need more information. Thanks.

**Comment by nadege** [comment] 2017-06-03 15:20
Hello!
Thank you for reporting this issue.
It was indeed caused by the package, it's fixed in version 0.3.1 which was just released!

**Closed as completed by nadege** 2017-06-03 15:20 UTC
